name: My first pipeline

on:
  push:
    branches:
      - main

jobs:
  show-config:
    runs-on: ubuntu-latest
    env:
      DB_PASS: ${{ secrets.DB_PASSWORD}}
      SRV_NAME: ${{ vars.SERVER_NAME}}
    steps:
      - name: show server name(variable -- visible in logs)
        run: echo "Deploying to server" "$SRV_NAME"

      - name: use password (secretn-- masked in log)
        run: echo "connecting with password:" "$DB_PASS"

