name: My first pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build step running"
          sleep 5

  test:
    needs: build    #waits for build to finish
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Test step running"
          sleep 5

  deploy:
    needs: test #waits for test to finish
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy step running -- all tests passed!"
